In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
T = 8 # sequence lenght
D = 2 # input dimensionally
M = 3 # hidden layer size

In [3]:
#input data
X = np.random.randn(1, T, D)
X

array([[[-0.00983864, -0.31823048],
        [-0.03923597, -0.10422375],
        [ 0.06553798, -0.91958912],
        [-0.827663  , -0.02614867],
        [ 1.14380037, -0.50513966],
        [ 0.5080553 ,  0.75281749],
        [ 1.05986019, -0.41528536],
        [ 0.06617076,  0.76918914]]])

In [4]:
X.shape

(1, 8, 2)

In [5]:
def lstm1():
    input_ = tf.keras.layers.Input(shape=(T,D))
    rnn = tf.keras.layers.LSTM(M, return_state=True)
    x = rnn(input_)
    
    model = tf.keras.models.Model(inputs=input_, outputs=x)
    output, hidden_state, cell_state = model.predict(X)
    print("o:", output)
    print("h:", hidden_state)
    print("c:", cell_state)

In [10]:
print("LSTM1")
lstm1()

LSTM1
Instructions for updating:
Colocations handled automatically by placer.
o: [[-0.02207665  0.07227381 -0.05333483]]
h: [[-0.02207665  0.07227381 -0.05333483]]
c: [[-0.05227917  0.15368944 -0.09363189]]


In [6]:
def lstm2():
    input_ = tf.keras.layers.Input(shape=(T,D))
    rnn = tf.keras.layers.LSTM(M, return_state=True, return_sequences=True)
    x = rnn(input_)
    
    model = tf.keras.models.Model(inputs=input_, outputs=x)
    output, hidden_state, cell_state = model.predict(X)
    print("o:", output)
    print("h:", hidden_state)
    print("c:", cell_state)

In [8]:
def gru1():
    input_ = tf.keras.layers.Input(shape=(T,D))
    rnn = tf.keras.layers.GRU(M, return_state=True)
    x = rnn(input_)
    
    model = tf.keras.models.Model(inputs=input_, outputs=x)
    output, hidden_state = model.predict(X)
    print("o:", output)
    print("h:", hidden_state)

In [9]:
def gru2():
    input_ = tf.keras.layers.Input(shape=(T,D))
    rnn = tf.keras.layers.GRU(M, return_state=True, return_sequences=True)
    x = rnn(input_)
    
    model = tf.keras.models.Model(inputs=input_, outputs=x)
    output, hidden_state = model.predict(X)
    print("o:", output)
    print("h:", hidden_state)

In [11]:
print("LSTM2")
lstm2()

LSTM2
o: [[[ 0.0473949  -0.0056427  -0.01469101]
  [ 0.04244686 -0.00517191 -0.01969806]
  [ 0.16462293 -0.02692981 -0.04223761]
  [ 0.0279924   0.02729038 -0.12939805]
  [ 0.15439743 -0.05863091 -0.01606023]
  [ 0.09849679 -0.0546859   0.10537602]
  [ 0.18044414 -0.1100691   0.19881822]
  [ 0.08450843 -0.04698319  0.19325596]]]
h: [[ 0.08450843 -0.04698319  0.19325596]]
c: [[ 0.16808558 -0.09487283  0.39882183]]


In [12]:
print("GRU1")
gru1()

GRU1
o: [[-0.00812505  0.09305971 -0.3293749 ]]
h: [[-0.00812505  0.09305971 -0.3293749 ]]


In [13]:
print("GRU2")
gru2()

GRU2
o: [[[ 0.10620001  0.07343073 -0.07598447]
  [ 0.07762659  0.05406353 -0.06170877]
  [ 0.33463904  0.2597465  -0.23737052]
  [ 0.02310511  0.06621186 -0.2631722 ]
  [ 0.2586371   0.33380324 -0.03090864]
  [-0.04775038  0.06180787  0.15793678]
  [ 0.18798494  0.20616788  0.1656268 ]
  [-0.12405092 -0.05472395  0.22693232]]]
h: [[-0.12405092 -0.05472395  0.22693232]]
